---
 
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (AlmaLinux)
    tags: always
    dnf:
        update_cache: yes
    changed_when: false
    when: ansible_distribution == "AlmaLinux"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
        update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Install updates (Archlinux-based)
    tags: always,archup
    community.general.pacman:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Archlinux"

- hosts: all
  become: true
  roles:
    - base
 
- hosts: web_servers
  become: true
  roles:
    - web_servers
 
- hosts: db_servers
  become: true
  roles:
    - db_servers
 
- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstation
  become: true
  roles:
    - workstation
