---

- hosts: all
  become: true
  tasks:

# apt
  - name: Remove apache & php package
    package:
        update_cache: yes
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
    when: ansible_pkg_mgr != "pacman"

# Pacman
  - name: Remove caddy on arch machine
    community.general.pacman:
        update_cache: yes
        name: 
          - caddy
        state: absent
    when: ansible_pkg_mgr == "pacman"


